---
ssh_data_path: "{{ ssh_home }}/.ssh"
ssh_config_file: "{{ ssh_data_path }}/config"
ssh_known_hosts_file: "{{ ssh_data_path }}/known_hosts"
ssh_priv_key_file: "{{ ssh_data_path }}/private_keys/github.pem"
ssh_priv_key_src: "private_keys/{{ ssh_priv_key_file | basename }}"
