---
- hosts: build-linux-slaves

  roles:
    - hwe
    - kamaln7.swapfile
    - geerlingguy.ntp

- hosts: build-linux-64-slaves

  roles:
    - geerlingguy.nodejs
    - geerlingguy.pip
    - geerlingguy.docker
    - ds-builder
    - qt
    - dockerhub-user
# Don't uncomment lines below, it runs in buildserver.yaml
#    - github-user
#    - sourceforge-user
#    - aws-cli
