---
- hosts:
    - build-windows-64-slaves
    - build-windows-32-slaves
  
  roles:
    - ds-builder
    - role: aws-cli
      user_profile_path: C:\Msys
    - role: github-user
      user_profile_path: C:\Msys

- hosts: build-windows-slaves

  roles:
    - aws-cli
    - github-user
    - exe-signer
    - vs-license
