---
- hosts: build-linux-slaves

  roles:
    - hwe
    - kamaln7.swapfile
    - geerlingguy.ntp
    - geerlingguy.nodejs
    - geerlingguy.pip

    - ds-builder
    - tb-builder
# Don't uncomment lines below, it runs in buildserver.yaml
#    - github-user
#    - aws-cli

- hosts: build-linux-64-slaves

  roles:
    - geerlingguy.docker