---
- hosts: buildserver-linux-slaves

  roles:
    - hwe
    - kamaln7.swapfile
    - geerlingguy.ntp
    - geerlingguy.nodejs
    - geerlingguy.pip

    - ds-builder
    - github-user

- hosts: buildserver-linux-64-slaves

  roles:
    - geerlingguy.docker

- hosts: buildserver-windows-slaves
  
  roles:
    - ds-builder