---
- hosts: buildserver-linux-slaves

  roles:
    - hwe
    - kamaln7.swapfile
    - geerlingguy.ntp
    - geerlingguy.nodejs
    - geerlingguy.pip

    - ds-builder
    - tb-builder
    - github-user
    - aws-cli

- hosts: buildserver-linux-64-slaves

  roles:
    - geerlingguy.docker