---
- hosts: build-linux-slaves

  roles:
    - hwe
    - kamaln7.swapfile
    - geerlingguy.ntp
    - geerlingguy.pip

- hosts: build-linux-64-slaves

  roles:
    - geerlingguy.nodejs
    - geerlingguy.docker
    - ds-builder
    - qt
    - astra-signer
    - ftp-user
    - dockerhub-user
# Don't uncomment lines below, it runs in buildserver.yaml
#    - github-user
#    - aws-cli

- hosts: build-linux-tb-slaves

  roles:
    - tb-builder
