---
- name: Check developer.apple.com/account
  uri:
    url: https://developer.apple.com/account/
  register: apple_account_response

- name: Set variables
  set_fact:
    apple_api_key: "{{ apple_account_response.url | urlsplit('query') | regex_replace('.*appIdKey=(.{64}).*', '\\1') }}"
    apple_frame_id: "auth-{{ 999999999999999999995 | random | to_uuid | regex_replace('(.{32}).*', '\\1') }}"
    apple_response_type: "code"
    apple_response_mode: "web_message"
    apple_cookies: "{{ apple_account_response.cookies_string }}"

- name: Authenticate Apple ID account
  uri:
    url: "https://idmsa.apple.com/appleauth/auth/authorize/signin?frame_id={{ apple_frame_id }}&language=US-EN&iframeId={{ apple_frame_id }}&client_id={{ apple_api_key }}&redirect_uri=https://idmsa.apple.com&response_type={{ apple_response_type }}&response_mode={{ apple_response_mode }}&state={{ apple_frame_id }}"
    headers:
      Cookie: "{{ apple_cookies }}"
  register: apple_auth_response

- name: Save cookies
  set_fact:
    apple_cookies: "{{ apple_cookies }}; aa={{ apple_auth_response.cookies.aa }}"

- name: Sign in Apple ID account
  uri:
    url: https://idmsa.apple.com/appleauth/auth/signin
    method: POST
    body_format: json
    body:
      accountName: "{{ appleid_email }}"
      rememberMe: "false"
      password: "{{ appleid_password }}"
    headers:
      Content-Type: application/json
      X-Apple-Widget-Key: "{{ apple_api_key }}"
      X-Apple-App-Id: "632"
      X-Apple-Frame-Id: "{{ apple_frame_id }}"
      X-Apple-OAuth-Client-Id: "{{ apple_api_key }}"
      X-Apple-OAuth-State: "{{ apple_frame_id }}"
      X-Apple-OAuth-Redirect-URI: https://idmsa.apple.com
      X-Apple-OAuth-Response-Type: "{{ apple_response_type }}"
      X-Apple-OAuth-Response-Mode: "{{ apple_response_mode }}"
      X-Apple-OAuth-Client-Type: firstPartyAuth
      X-Apple-Locale: US-EN
      X-Requested-With: XMLHttpRequest
      Cookie: "{{ apple_cookies }}"
    follow_redirects: all
  register: apple_signin_response

- name: Save cookies
  set_fact:
    apple_cookies: "{{ apple_cookies }}; myacinfo={{ apple_signin_response.cookies.myacinfo }}"

- name: Get Apple Developer download cookies
  uri:
    url: https://developer.apple.com/services-account/QH65B2/downloadws/listDownloads.action
    method: POST
    headers:
      Cookie: "{{ apple_cookies }}"
  register: apple_developer_response

- name: Save cookies
  set_fact:
    apple_cookies: "{{ apple_cookies }}; DSESSIONID={{ apple_developer_response.cookies.DSESSIONID }}; ADCDownloadAuth={{ apple_developer_response.cookies.ADCDownloadAuth }}"
    apple_download_cookies: "{{ apple_developer_response.set_cookie }}"
