---
  - name: "Get private key content"
    command: "openssl rsa -in {{ jenkins_home }}/.ssh/{{ jenkins_private_keyname }} -check"
    register: ssh_private_key
    changed_when: False

  - name: Execute add slave credential
    jenkins_script:
      script: "{{ lookup('template', 'add-credentials.groovy.jn2')}}"
      user: "{{ jenkins_admin_username }}"
      password: "{{ jenkins_admin_password }}"
      url: "http://localhost:{{ jenkins_http_port }}/" 