---
- name: Execute add-ssh-slave script
  jenkins_script:
    script: "{{ lookup('template', 'add-ssh-slave.groovy.jn2')}}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:{{ jenkins_http_port }}/"

- name: Execute add-win-slave script
  jenkins_script:
    script: "{{ lookup('template', 'add-win-slave.groovy.jn2')}}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:{{ jenkins_http_port }}/"
