---
- name: Install Thunderbird build dependencies
  package:
    name: "{{ packages }}"
  vars:
    packages:
    - autoconf2.13
    - build-essential
    - createrepo
    - debhelper
    - dpkg-dev
    - git
    - libasound2-dev
    - libcurl4-openssl-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libgconf2-dev
    - libgtk-3-dev
    - libgtk2.0-dev
    - libpulse-dev
    - libx11-xcb-dev
    - libxt-dev
    - nodejs
    - python-dbus
    - python-dev
    - python-pip
    - python-setuptools
    - symlinks
    - unzip
    - uuid
    - xvfb
    - yasm
    - zip
