---
- name: Install Thunderbird build dependencies
  package:
    name: "{{ packages }}"
    force: yes 
  become: yes

- name: Install Rust's cbindgen
  command: cargo install cbindgen -q --force
  become: yes
  become_user: "{{ ssh_user }}"
