---
- name: Remove Windows Defender
  win_feature:
    name: Windows-Defender
    state: absent
  register: win_feature
  changed_when: win_feature.reboot_required
  notify: restart-server
  when: ansible_os_product_type == "server"

- name: Create download directory
  win_file:
    path: "{{ download_path }}"
    state: directory

- name: Download Visual Studio Community 2017
  win_get_url:
    url: https://download.visualstudio.microsoft.com/download/pr/dd3eb7bc-5549-45f2-be9a-80984f4d4d90/3f078bd1dfac460c311142b1f8dad6c840bc03237511f4fd983812bb65ec5bd5/vs_Community.exe
    dest: "{{ download_path }}\\vs_community_2017.exe"
    force: no

- name: Copy .vsconfig
  win_copy:
    src: vs/.vsconfig
    dest: "{{ download_path }}\\.vsconfig"

- name: Download Visual C++ Compiler for Python 2.7
  win_get_url:
    url: https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi
    dest: "{{ download_path }}\\vc_for_python27.msi"
    force: no

- name: Download MAPI Header Files
  win_get_url:
    url: https://download.microsoft.com/download/B/6/4/B645F2C9-715A-4EAB-B561-CC0C9779C249/Outlook2010MAPIHeaders.EXE
    dest: "{{ download_path }}\\mapiheaders.exe"
    force: no

- name: Extract MAPI Header Files
  win_package:
    path: "{{ download_path }}\\mapiheaders.exe"
    creates_path: "{{ download_path }}\\OUTLOO~1.EXE"
    arguments: "/Q /T:{{ download_path }} /C"

- name: Extract MAPI Header Files (WinZip Self-Extractor)
  win_package:
    path: "{{ download_path }}\\OUTLOO~1.EXE"
    creates_path: "{{ download_path }}\\MAPI"
    arguments: "/auto {{ download_path }}\\MAPI"

- name: Download mozilla-build package
  win_get_url:
    url: https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe
    dest: "{{ download_path }}\\mozillabuild.exe"
    force: no

- name: Download Rust
  win_get_url:
    url: https://win.rustup.rs/x86_64
    dest: "{{ download_path }}\\rustup-init.exe"
    force: no

- name: Download Java
  win_get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-windows-x64.exe
    headers: 
      Cookie: "oraclelicense=accept-securebackup-cookie"
    dest: "{{ download_path }}\\java.exe"
    force: no

- name: Download Git
  win_get_url:
    url: https://npm.taobao.org/mirrors/git-for-windows/v2.21.0.windows.1/Git-2.21.0-64-bit.exe
    dest: "{{ download_path }}\\git.exe"
    force: no

- name: Download Inno Setup 6
  win_get_url:
    url: http://files.jrsoftware.org/is/6/innosetup-6.0.4.exe
    dest: "{{ download_path }}\\is-unicode.exe"
    force: no

- name: Download AWSCLI
  win_get_url:
    url: https://s3.amazonaws.com/aws-cli/AWSCLI64.msi
    dest: "{{ download_path }}\\aws-cli.msi"
    force: no

- name: Install Visual Studio Community 2017
  win_package:
    path: "{{ download_path }}\\vs_community_2017.exe"
    creates_path: "{{ program_files_32 }}\\Microsoft Visual Studio\\2017\\Community"
    arguments: "--quiet --norestart --wait --config \"{{ download_path }}\\.vsconfig\""
  notify: restart-server

- name: Install Visual C++ Compiler for Python 2.7
  win_package:
    path: "{{ download_path }}\\vc_for_python27.msi"
    product_id: "{692514A8-5484-45FC-B0AE-BE2DF7A75891}"

- name: Copy MAPI Header Files
  win_copy:
    src: "{{ download_path }}\\MAPI\\"
    dest: "{{ item }}\\"
    remote_src: yes
    force: no
  with_items:
    - "{{ program_files_32 }}\\Windows Kits\\10\\Include\\10.0.17134.0\\shared"
    - "{{ program_files_32 }}\\Windows Kits\\10\\Include\\10.0.17763.0\\shared"

- name: Install mozilla-build package
  win_package:
    path: "{{ download_path }}\\mozillabuild.exe"
    creates_path: C:\mozilla-build
    arguments: /S

- block:
    - name: Install Rust
      win_command: .\rustup-init.exe -q --profile minimal -y
      args:
        chdir: "{{ download_path }}"

    - name: Install Rust's cbindgen
      win_command: cargo install cbindgen -q --force
      args:
        creates: "{{ user_profile_path }}\\.cargo\\bin\\cbindgen.exe"

  become: yes
  become_method: runas
  become_user: LocalService

- name: Install Java
  win_package:
    path: "{{ download_path }}\\java.exe"
    product_id: '{26A24AE4-039D-4CA4-87B4-2F64180131F0}'
    arguments: INSTALL_SILENT=Enable REBOOT=Disable SPONSORS=Disable

- name: Install Git
  win_package:
    path: "{{ download_path }}\\git.exe"
    product_id: 'Git_is1'
    arguments: /VERYSILENT /NORESTART

- name: Install Inno Setup 6
  win_package:
    path: "{{ download_path }}\\is-unicode.exe"
    product_id: 'Inno Setup 6_is1'
    arguments: /VERYSILENT /NORESTART

- name: Install AWSCLI
  win_package:
    path: "{{ download_path }}\\aws-cli.msi"
    product_id: '{F8C04D08-B44A-4C1E-A6B4-EEF2390806DB}'
    arguments: /quiet /qn /norestart

- name: Set up PATH variable
  win_path:
    elements:
      - '{{ program_files_64 }}\Git\cmd'
      - '{{ program_files_32 }}\Inno Setup 6'
      - '{{ program_files_32 }}\Windows Kits\10\bin\10.0.17763.0\x64'
  notify: restart-server
