- name: Install requred packages
  apt: name={{ item }} force=yes 
  with_items:
  - "apt-transport-https"
  - "autoconf"
  - "build-essential"
  - "createrepo"        
  - "debhelper"
  - "desktop-file-utils"
  - "dpkg-dev"
  - "git"
  - "libatk1.0-dev"
  - "libcairo2-dev"
  - "libcurl4-gnutls-dev"
  - "libgconf2-dev"        
  - "libgdk-pixbuf2.0-dev"
  - "libglib2.0-dev"      
  - "libgtkglext1-dev"
  - "libtool"
  - "libxml2-dev"
  - "libxss-dev"
  - "p7zip-full"
  - "qtchooser"
  - "software-properties-common"
  - "sed"
  - "subversion"
  - "symlinks"
  - "tar"
  - "wget"
  - "unzip"
  become: yes

- name: Install java repo
  apt_repository:
    repo: "{{ java_repo }}"
    filename: java
  become: yes

- name: Accept java license
  debconf:
    name: "{{ java_package }}"
    question: shared/accepted-oracle-license-v1-1
    value: "true"
    vtype: select
  become: yes

- name: Set java license as seen
  debconf:
    name: "{{ java_package }}"
    question: shared/accepted-oracle-license-v1-1
    value: true
    vtype: seen
  become: yes

# - name: Set java license as seen
#   debconf:
#     name: "{{ java_package }}"
#     question: shared/present-oracle-license-v1-1
#     value: true
#     vtype: seen
#   become: yes

- name: Install java installer
  apt:
    name: "{{ java_package }}"
    force: yes
  become: yes

- name: Install qt repo
  apt_repository:
    repo: "{{ qt_repo }}"
    filename: qt

- name: Install qt
  apt:
    name: "{{ qt_package }}"
    force: yes

- name: Install patchelf repo
  apt_repository:
    repo: "{{ patchelf_repo }}"
    filename: qt

- name: Install patchelf
  apt:
    name: "{{ patchelf_package }}"
    force: yes

- name: Install grunt
  npm: name=grunt-cli global=yes
  become: yes
