---
ssh_home: "{{ ansible_env.HOME }}"
ssh_user: "{{ ansible_user }}"

git_user_name: user
git_user_email: email@example.com

github_cli_url: https://github.com/cli/cli/releases/download/v0.11.1/gh_0.11.1_linux_amd64.deb
