---
- name: Ensure jenkins exist
  stat:
    path: "{{ jenkins_home }}/init.groovy.d"
  become: yes
  register: jenkins_stat

- name: configure jenkins
  template:
    src: groovy/init.groovy.jn2
    dest: "{{ jenkins_home }}/init.groovy.d/init.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  when: jenkins_stat.stat.exists
  notify: restart-jenkins
