java_repo: ppa:webupd8team/java
java_package: oracle-java8-installer

qt_repo: ppa:beineri/opt-qt596-trusty
qt_package: qt59-meta-full

patchelf_repo: ppa:cjwatson/backports
patchelf_package: patchelf