---
- name: Install git
  package:
    name: git
  become: yes

- block:
  - name: Config git user.name
    git_config:
      name: user.name
      scope: global
      value: "{{ git_user_name }}"

  - name: Config git user.email
    git_config:
      name: user.email
      scope: global
      value: "{{ git_user_email }}"
  become: yes
  become_user: "{{ ssh_user }}"

- name: Copy ssh config
  template:
    src: "ssh/config.jn2"
    dest: "{{ ssh_config_dest }}"
    mode: "0600"
  become: yes
  become_user: "{{ ssh_user }}"

- name: Create private keys directory
  file:
    path: "{{ ssh_priv_key_dest }}"
    state: "directory"
  become: yes
  become_user: "{{ ssh_user }}"

- name: Copy github private key
  copy: 
    src: "{{ ssh_priv_key_src }}"
    dest: "{{ ssh_priv_key_dest }}"
    mode: "0600"
  become: yes
  become_user: "{{ ssh_user }}"

- name: Ensure github.com is a known host
  lineinfile:
    dest: "{{ ssh_home }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
  become: yes
  become_user: "{{ ssh_user }}"

- name: Install jq
  apt: 
    name: jq
  become: yes

- name: Install gh
  apt:
    deb: "{{ github_cli_url }}"
  become: yes

- block:
  - name: Create gh config directory
    file:
      path: "{{ ssh_home }}/.config/gh"
      state: directory
      mode: 0755

  - name: Copy gh config.yml
    copy:
      src: "gh/config.yml"
      dest: "{{ ssh_home }}/.config/gh/config.yml"

  - name: Copy gh hosts.yml
    template:
      src: "gh/hosts.yml.jn2"
      dest: "{{ ssh_home }}/.config/gh/hosts.yml"
  become: yes
  become_user: "{{ ssh_user }}"
