- name: Copy ssh config
  template:
    src: "ssh/config.jn2"
    dest: "{{ ssh_config_dest }}"
    mode: "0600"

- name: Create private keys directory
  file:
    path: "{{ ssh_priv_key_dest }}"
    state: "directory"

- name: Copy github private key
  copy: 
    src: "{{ ssh_priv_key_src }}"
    dest: "{{ ssh_priv_key_dest }}"
    mode: "0600"

- name: Ensure github.com is a known host
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"