---
- name: Create ssh data directory
  win_file:
    path: "{{ ssh_data_path }}"
    state: "directory"

- name: Copy ssh config
  win_template:
    src: "ssh/config.jn2"
    dest: "{{ ssh_config_file }}"

- name: Create ssh private keys directory
  win_file:
    path: "{{ ssh_priv_key_file | win_dirname }}"
    state: "directory"

- name: Copy github private key
  win_copy: 
    src: "{{ ssh_priv_key_src }}"
    dest: "{{ ssh_priv_key_file }}"

- name: Ensure github.com is a known host
  win_lineinfile:
    dest: "{{ ssh_known_hosts_file }}"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
